name: Github Actions Demo
run-name: ${{github.workflow}} is testing out Github Actions ğŸš€
on: [push,workflow_dispatch]
jobs:
    Explore-Github-Actions:
      runs-on: ubuntu-latest
      steps:
        - run: echo "ğŸ‰ The job was automatically triggered by a ${{github.event_name}} event"
        - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server"
        - run: echo "ğŸ” The name of your branch is ${{github.ref}} and your repository is ${{github.repository}}" 
        - name: Checkout Repository Code
          uses: actions/checkout@v6  
        - run: echo "ğŸ’¡ The ${{github.repository}} repository has been cloned to the runner ${{runner.os}} server"
        - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
        - name: List files in the repository
          run: |
            ls -l ${{github.workspace}}
        - run: echo "âœ… The job has been completed successfully!"
        - run: echo "ğŸ The workflow has finished running with status ${{job.status}}!"
